"""notification state and incident end reason

Revision ID: a8b118bf7e64
Revises: d6f366b3d292
Create Date: 2026-09-16 22:05:57.025502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b118bf7e64'
down_revision: Union[str, Sequence[str], None] = 'd6f366b3d292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('down_notified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('incidents', sa.Column('end_reason', sa.String(length=20), nullable=True))
    op.add_column('incidents', sa.Column('notifications_skipped', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    # Уже существующие данные: закрытые до этой миграции инциденты закрывались
    # только восстановлением; все уже отправленные уведомления считаем обработанными,
    # а текущие "DOWN отправлено, RECOVERED нет" переносим на уровень проверки.
    op.execute("UPDATE incidents SET end_reason = 'recovered' WHERE ended_at IS NOT NULL")
    op.execute(
        "UPDATE incidents SET notifications_skipped = true "
        "WHERE ended_at IS NOT NULL AND alert_down_sent_at IS NULL AND alert_recovered_sent_at IS NOT NULL"
    )
    op.execute(
        "UPDATE checks SET down_notified = true WHERE EXISTS ("
        "  SELECT 1 FROM incidents i WHERE i.check_id = checks.id"
        "  AND i.alert_down_sent_at IS NOT NULL AND i.alert_recovered_sent_at IS NULL)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'notifications_skipped')
    op.drop_column('incidents', 'end_reason')
    op.drop_column('checks', 'down_notified')
    # ### end Alembic commands ###
